export default {
  GOODS_ACTION: 'GOODS_ACTION',
  GOODS_RESPONSE: 'GOODS_RESPONSE',
  GOODS_REQUEST: 'GOODS_REQUEST',
  GOODS_ERROR: 'GOODS_ERROR',
  SINGLE_GOODS_ACTION: 'SINGLE_GOODS_ACTION',
  SINGLE_GOODS_RESPONSE: 'SINGLE_GOODS_RESPONSE',
  UPDATE_SINGLE_GOODS_ACTION: 'UPDATE_SINGLE_GOODS_ACTION',
};
