export default {
  TEST_ACTION:"TEST_ACTION",

  AUTH_ACTION: "AUTH_ACTION",


  AUTH_REQUEST:"AUTH_REQUEST",
  AUTH_RESPONSE:"AUTH_RESPONSE",
  AUTH_ERROR:"AUTH_ERROR",
  SAY_HELLO_ACTION: "SAY_HELLO_ACTION"
}